package com.nic.java8.stream;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class StreamMap {
	
	public static void main(String [] args){
		
		List<String> listOfStrings = Arrays.asList("1", "2", "3", "4", "5");
		List<Integer> listOfIntegers =listOfStrings.stream().map(Integer::valueOf)
				                      .collect(Collectors.toList());
		System.out.println("listOfIntegers: "+listOfIntegers);
		
		//flatMap
		
		System.out.println("======FlatMap=======");
		List<Integer> evens = Arrays.asList(2, 4, 6);
		List<Integer> odds = Arrays.asList(3, 5, 7);
		List<Integer> primes = Arrays.asList(2, 3, 5, 7, 11);
		
		List<Integer> listArr=   Stream.of(evens,odds,primes)
						         .flatMap(list->list.stream())
						         .collect(Collectors.toList());
		System.out.println(listArr);
		          
		          
		 List<String> loseWeight = new ArrayList<>();
	        loseWeight.add("avocados");
	        loseWeight.add("beans");
	        loseWeight.add("salad");
	        loseWeight.add("oats");
	        loseWeight.add("broccoli"); 
	        
	        System.out.println("list of String : " + loseWeight);
	        
	        // let's use map() method to convert list of weight lose food,
	        //  which are String to list of ints
	        // which are length of each food String
	         
	        List<Integer> weightList=loseWeight.stream().map(s -> s.length())
	                  .collect(Collectors.toList());
	        System.out.println("weightList: "+weightList);   
	        
	     // flatMap() example, let's first creat a list of list
	        List<List> listOfListOfNumber = new ArrayList<>();
	        listOfListOfNumber.add(Arrays.asList(2, 4));
	        listOfListOfNumber.add(Arrays.asList(3, 9));
	        listOfListOfNumber.add(Arrays.asList(4, 16));
	        
	        System.out.println("list of list : " + listOfListOfNumber);
	        
	  List<Stream> ayy=   listOfListOfNumber.stream().map( list1 -> list1.stream()).collect(Collectors.toList());
	        
	        System.out.println("list of numbers generated by flatMap : "+ayy.getClass());
	        
	        ArrayList<Product> list=new ArrayList<>();
	        list.add(new Product(1, "Kamlesh", 200));
	        list.add(new Product(2, "Saurabh", 300));
	        list.add(new Product(3, "Tarun", 400));
	        list.forEach(s->System.out.println(s.id+" "+s.name+" "+s.price));
	        
	}
	


}
